- client/app/dashboard/model/list/ModelList.js
adds load start emitter at the beginning of LoadItems method;
ready for code review;
> adds load start emitter at the beginning of LoadItems method;

- client/app/dashboard/model/edit/ModelEdit.styl
- client/common/directives/ModelFieldPointsOfInterest/ModelFieldPointsOfInterest.js
> model-field-points-of-interest

- client/app/dashboard/model/edit/ModelEdit.styl
- client/css/main.css
Fixes a css issue causing the map in ModelFieldLocation to not render due to a 0 height. May be related to edfec53d0a9a107439a9547a5a1a5a63cae70c32.
> fix css bug preventing map from rendering

- client/app/dashboard/model/edit/ModelEdit.styl
- client/common/directives/ModelFieldWYSIWYG/ModelFieldWYSIWYG.js
- client/css/main.css
- fixes issue with wysiwyg field when used multiple times in a page, isolate formatting to own editor instance instead of all instances
- implements the color picker
- implements the font size selector
> Adds font color and font size selectors on the toolbar

- client/app/dashboard/model/list/ModelList.js
Added a deleteRowWithMessage which utilizes the deleteRow method and accepts a custom confirm message
> Add delete row method that accepts custom confirm message

- client/common/directives/ModelField/ModelField.js
This is required for the select all/deselect all feature to work
> emit event when multiselect option is clicked

- client/app/dashboard/model/DashboardModel.jade
- client/app/dashboard/model/nav/ModelNav.js
Added ability to add classes to individual labels in the cmd-config.json file
> Add classes to nav labels

- client/app/app.js
- client/app/login/Login.js
Adds ability to redirect user to desired state/url route after signing in
> Redirect users to desired URL after signing in.

- client/app/dashboard/alert/Alert.jade
- client/app/dashboard/alert/Alert.js
- client/index.jade
> extend Alert Controller to allow confirm dialogue

- client/common/directives/ModelFieldReference/ModelFieldReference.js
> Refresh pull down options on field focus

- client/common/directives/ModelFieldReference/ModelFieldReferenceSort.js
> Add check for duplicate names

- client/common/directives/ModelFieldPointsOfInterest/ModelFieldPointsOfInterest.js
> [DD-425] reset bounds between searches

- client/common/directives/ModelFieldImage/ModelFieldImage.js
Added Confirmation Dialog when clearing concern photos.
> Added Confirmation dialog for Clearing Concern Photos.

- client/common/directives/ModelFieldPointsOfInterest/ModelFieldPointsOfInterest.js
- Accepts Google Api Key
- Uses type instead of types (Place Types)
> Fix googlemaps deprecated issues

- client/common/directives/ModelFieldFile/ModelFieldFile.js
> add button to clear ModelFieldFile

- client/common/directives/ModelFieldReference/ModelFieldReference.js
Added support for “allowInsert” on a type “reference” with multiple set to true.
> Added support for “allowInsert” on a type “reference” (multiple = true)

- client/common/directives/DateTimePicker/DateTimePicker.js
Fixes date value changes not immediately propagating between ngModel and datepicker
> SE: DateTimePicker two-way binding

- client/common/directives/ModelField/ModelField.js
fix lexer errors caused by regex patterns on directive templates
> fix lexer errors caused by regex patterns on directive templates

- client/app/app.js
> add back button to access denied page

- client/common/directives/ModelFieldImage/ModelFieldImage.js
- client/common/services/ImageService.js
DD-1160 The uploaded photos disappear when clicking Concern and back to Photo tab
> load image field from __ModelFieldImageData object

- client/common/services/SessionService.js
> Set session = null on logout
